build: Remove ci-nightly.yml
Removed it because there are warnings that actions were using Node 12
and needed to be updated to support Node 16 as well as many lint warnings.

Changed ci-stable.yml to hopefully fix the Node12 warnings and disabled
"coverage" as I'm getting an error:
  Error: config value 'safe.directory' was not found; class=Config (7); code=NotFound (-3)

Fix clippy warning in process_binance_com.rs