Example of trying to get async ProcessLine working
This doesn't compile as seen below. I gave up for now and instead of using
closures and function pointers in the other branch,
Support-async-processing-line, it's hard coded. Which is easy to understand
does the job, although it is not composable :(

 wink@3900x:~/prgs/rust/myrepos/binance-cli (Add-binance-distribution-processing)
 $ cargo build
   Compiling binance-cli v0.3.2 (/home/wink/prgs/rust/myrepos/binance-cli)
 error[E0277]: the size for values of type `dyn Future<Output = Result<(), Box<(dyn StdError + 'static)>>>` cannot be known at compilation time
    --> src/binance_distribution_processing.rs:202:9
     |
 202 |         process_line(config, data, &mut dr, line_index).await?;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
     |
     = help: the trait `Sized` is not implemented for `dyn Future<Output = Result<(), Box<(dyn StdError + 'static)>>>`
     = note: all local variables must have a statically known size
     = help: unsized locals are gated as an unstable feature

 error[E0308]: mismatched types
     --> src/binance_distribution_processing.rs:386:9
     |
 386 |         process_hm_entry,
     |         ^^^^^^^^^^^^^^^^ expected trait object `dyn Future`, found enum `Result`
     |
     = note: expected fn pointer `for<'r, 's, 't0> fn(&'r Configuration, &'s mut ProcessedData, &'t0 mut DistRec, _) -> (dyn Future<Output = Result<(), Box<(dyn StdError + 'static)>>> + 'static)`
                  found fn item `for<'r, 's, 't0> fn(&'r Configuration, &'s mut ProcessedData, &'t0 mut DistRec, _) -> Result<(), Box<(dyn StdError + 'static)>> {process_hm_entry}`

 Some errors have detailed explanations: E0277, E0308.
 For more information about an error, try `rustc --explain E0277`.
 error: could not compile `binance-cli` due to 2 previous errors