Change part of the test_convert to BNB to BUSB
As it sometimes fails when converting to USD:

  ---- binance_trade::test::test_convert stdout ----
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "convert error, asset: BNB not convertable to USD"', src/binance_trade.rs:396:14